# -*- coding: utf-8 -*-
"""evaluación 3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpQKh9hNJsqN_IhW4tVDpdgWdiPhnf_W
"""

import csv

registro_trabajadores = []
nombre_apellido = ""
cargo = ""
sueldo_liquido = 0
sueldo_bruto = 0
descuento_salud = 0
descuento_afp = 0
cocinero = ""
mesero= ""
cajero = ""
opc=0
total= 0
salir = ""



if opc1 != nombre_apellido:
  print("ingrese nombre y apellido: ")
  input("")

  if opc2 != cargo or cocinero or mesero or cajero:
   print("error elige un cargo ")
   input("elige que cargo desea:  ")

   if opc3 == sueldo_liquido == {descuento_afp %10}:
      sueldo_bruto - descuento_afp %10
      descuento_afp = descuento_afp = total
      print("ver total descuento_afp: ")
      input(" ")


      if opc4 == sueldo_liquido == {descuento_salud %7}:
         sueldo_bruto - descuento_salud %7
         descuento_salud = descuento_salud = total
         print("ver total descuento_salud: ")
         input(" ")

         if opc5 == sueldo_liquido == sueldo_bruto
         sueldo_liquido += sueldo_bruto
         sueldo_liquido = sueldo_liquido = total
         print("ver total sueldo_liquido")
         input(" ")

         if opc6 == registro_trabajadores
         print(registro_trabajadores.append[nombre_apellido, cargo, sueldo_liquido, sueldo_bruto, descuento_afp, descuento_salud])

         if opc7 == salir
        break


         print(-------
             MENU
      opc1- ingrese nombre y apellido
      opc2- ingrese el cargo que desea
      opc3- sueldo liquido con descuento_afp
      opc4 -sueldo liquido con descuento_salud
      opc5_ sueldo liquido
      opc6- mostrar registro de trabajador
      opc7_ salir

               ------)